FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1         

RUN apt-get update && apt-get install -y git

WORKDIR /app

# Clone the repository and set the working directory to it
RUN git clone https://github.com/Bryantgouw/motor-service-api-final-revision.git /app/motor-service-api-final-revision
WORKDIR /app/motor-service-api-final-revision

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8033

# Set the default command to run the service
CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8033"]
