# Gunakan base image Python versi 3.12
FROM python:3.12

# Nonaktifkan bytecode dan buffer output Python
ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1         

# Update sistem dan install git
RUN apt-get update && apt-get install -y git

# Set working directory
WORKDIR /app

# Salin semua file dari direktori lokal ke dalam container
COPY . /app

# Install dependencies dari requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Ekspos port aplikasi
EXPOSE 8033

# Set perintah default untuk menjalankan aplikasi
CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8033"]