FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1         

RUN apt install git

WORKDIR /app

RUN git clone https://github.com/Bryantgouw/motor-service-api-final-revision.git

RUN cd motor-service-api-final-revision && pip install --no-cache-dir -r requirements.txt

EXPOSE 8033

CMD ["uvicorn", "service:app", "--host", "0.0.0.0", "--port", "8033"]